version: '3.9'

services:
  db:
    env_file:
      - ./.env
    ports:
      - 5432:5432
    container_name: db
    image: postgres:15
    volumes:
      - api_db:/var/lib/postgresql/data
    restart: always

  flask:
    container_name: english_api
    env_file:
      - ./.env
    image: alexseipopov/english_api
    restart: always
    ports:
      - 3015:3015
    volumes:
      - api_storage:/var/lib/app_data
    depends_on:
      - db
    links:
      - db

  

volumes:
    api_db:
      driver: local
    api_storage:
      driver: local

