"""empty message

Revision ID: 79256f101799
Revises: d8c26899672d
Create Date: 2023-04-24 14:17:23.757153

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '79256f101799'
down_revision = 'd8c26899672d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example_en', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('transcription', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('example_ru', sa.Text(), nullable=False))
        batch_op.drop_column('example')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('example_ru')
        batch_op.drop_column('transcription')
        batch_op.drop_column('example_en')

    # ### end Alembic commands ###
