"""empty message

Revision ID: 84bb7441fdf2
Revises: 79256f101799
Create Date: 2023-04-24 14:31:12.199648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84bb7441fdf2'
down_revision = '79256f101799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__has__word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__has__word',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name='user__has__word_status_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user__has__word_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name='user__has__word_word_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user__has__word_pkey')
    )
    # ### end Alembic commands ###
