"""empty message

Revision ID: a35fe396b9ff
Revises: cbddab228934
Create Date: 2023-03-19 12:12:42.121703

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a35fe396b9ff'
down_revision = 'cbddab228934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_en', sa.Text(), nullable=False),
    sa.Column('word_ru', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Group')
    op.drop_table('Word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Word',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Word_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('word_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('word_ru', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('example', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], name='Word_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Word_pkey')
    )
    op.create_table('Group',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Group_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Group_pkey')
    )
    op.drop_table('word')
    op.drop_table('group')
    # ### end Alembic commands ###
