from english_api.swagger.profile.auth import auth
from english_api.swagger.profile.auth_swagger import register
from english_api.swagger.profile.change_password import change_password
from english_api.swagger.profile.check_auth import check_auth
from english_api.swagger.profile.delete import delete
from english_api.swagger.profile.recovery_password import recovery_password
from english_api.swagger.words.get_words import study_words
from english_api.swagger.words.know_this_word import know_this_word
from english_api.swagger.words.new_word import new_word
