name: Build, push and deploy app
on: [push]

jobs:
  build_and_push_docker_image:
    name: Build and push to docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        if: ${{ github.repository == 'alexseipopov/english_api' && github.ref == 'refs/heads/master' }}
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        if: ${{ github.repository == 'alexseipopov/english_api' && github.ref == 'refs/heads/master' }}
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/english_api:latest .
            docker push ${{ secrets.DOCKER_USERNAME }}/english_api:latest
  deploy:
    name: Deploy on server
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: SSH connect and deploy
        uses: appleboy/ssh-action@master
        if: ${{ github.repository == 'alexseipopov/english_api' && github.ref == 'refs/heads/master'}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd plus1org/
            docker-compose stop
            docker-compose down
            docker pull alexseipopov/english_api:latest
            docker-compose up -d
